name: Deploy Python project to Azure Web App

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: 'uebung5'   # Set this to your web app name on Azure
  AZURE_WEBAPP_PACKAGE_PATH: '.'          # Set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                   # Set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pulumi pulumi-azure-native

    - name: Pulumi Login
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      run: pulumi login

    - name: Pulumi Destroy
      run: pulumi destroy --yes

    - name: Pulumi Stack Select
      run: pulumi stack select dev

    - name: Pulumi Config Set
      run: |
        pulumi config set azure:location westus2
        pulumi config set azure:subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        pulumi config set azure:clientId ${{ secrets.AZURE_CLIENT_ID }}
        pulumi config set azure:clientSecret ${{ secrets.AZURE_CLIENT_SECRET }} --secret
        pulumi config set azure:tenantId ${{ secrets.AZURE_TENANT_ID }}

    - name: Pulumi Up
      run: pulumi up --yes