name: Deploy Python project to Azure Web App

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: 'uebung5'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create ZIP file
      run: |
        cd app
        zip -r ../webapp.zip .
      shell: bash

    - name: Pulumi Login
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      run: pulumi login

    - name: Pulumi Stack Init or Select
      run: |
        pulumi stack select dev || pulumi stack init dev
    - name: Pulumi Config Set
      run: |
        pulumi config set azure:location westus2
        pulumi config set azure:subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        pulumi config set azure:clientId ${{ secrets.AZURE_CLIENT_ID }}
        pulumi config set azure:clientSecret ${{ secrets.AZURE_CLIENT_SECRET }} --secret
        pulumi config set azure:tenantId ${{ secrets.AZURE_TENANT_ID }}
    - name: Pulumi Up
      run: |
        # Aktualisieren der Blob-Datei und Bereitstellung
        pulumi up --yes
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}