name: Deploy Python project to Azure Web App

on:
  push:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: 'uebung5'   
  AZURE_WEBAPP_PACKAGE_PATH: './webapp.zip'  # Set this to the path to your web app project
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pulumi pulumi-azure-native azure-storage-blob

    - name: Pulumi Login
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      run: pulumi login

    - name: Pulumi Stack Select
      run: pulumi stack select dev

    - name: Pulumi Destroy
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: pulumi destroy --yes

    - name: Pulumi Config Set
      run: |
        pulumi config set azure:location westus2
        pulumi config set azure:subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        pulumi config set azure:clientId ${{ secrets.AZURE_CLIENT_ID }}
        pulumi config set azure:clientSecret ${{ secrets.AZURE_CLIENT_SECRET }} --secret
        pulumi config set azure:tenantId ${{ secrets.AZURE_TENANT_ID }}

    - name: Create ZIP file
      run: |
        if [ -d "app" ]; then
          zip -r webapp.zip app
          echo "ZIP-Datei 'webapp.zip' wurde erfolgreich erstellt."
          ls -lh webapp.zip
        else
          echo "Directory 'app' does not exist"
          exit 1
        fi

    - name: Pulumi Up
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: pulumi up --yes