name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pulumi pulumi-azure-native

      - name: Pulumi Login
        run: pulumi login

      - name: Pulumi Stack Select
        run: pulumi stack select dev

      - name: Pulumi Config Set
        run: |
          pulumi config set azure:location westus2
          pulumi config set azure:subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          pulumi config set azure:clientId ${{ secrets.AZURE_CLIENT_ID }}
          pulumi config set azure:clientSecret ${{ secrets.AZURE_CLIENT_SECRET }}
          pulumi config set azure:tenantId ${{ secrets.AZURE_TENANT_ID }}

      - name: Pulumi Up
        run: pulumi up --yes
